---
- name: Install docker #Redundant plays
  hosts: all
  become: yes
  tasks:
  - name: Install Docker 
    yum: 
      name: docker
      update_cache: yes
      state: present
- name: Install Docker Compose  
  hosts: all
  become: yes
  tasks:
    - name: Install docker-compose
      get_url: 
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x     
- name: Start Docker
  hosts: all
  become: yes
  tasks:
    - name: Start docker daemon
      systemd: 
        name: docker
        state: started  
    - name: Install docker python module # Install docker python module needed to use docker module 
      pip:
        name: 
        - docker
        - docker-compose


- name: Add ec2 user to docker group
  hosts: all
  become: yes
  tasks:
    - name: Add ec2 user to docker group #We want to add user ec2 to docker group to perform docker commands without being sudo
      user: 
        name: ec2-user
        groups: docker
        append: yes # To add docker group to the groups
    - name: Reconnect to server session # Reconnect the server to add the user to group without restarting the server
      meta: reset_connection
- name: Test docker pull
  hosts: all
  tasks: 
    - name: Pull Redis
      docker_image:
        name: redis
        source: pull 
- name: Start Docker Containers
  hosts: all
  become: yes
  vars_files:
    - project-vars

  tasks:
    - name: Copy docker compose
      copy:
        src: /mnt/f/Work/Work/Atos/pet-clinic-task/spring-petclinic/petclinic/ #remote from
        dest: /home/ec2-user/petclinic
                    
                 
    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: aeramzy9
        password: "{{docker_password}}"
    
    - name: Start container from compose
      docker_compose:
        project_src: /home/ec2-user/petclinic # Run playbook to make sure containers are run
