import static io.wcm.devops.jenkins.pipeline.utils.ConfigConstants.*

 checkoutScm( 
        (SCM) : [
        (SCM_URL) :  "https://github.com/ahmedramzygi/petclinic" ,
        ]
    )  
continuous_integration()
