
// on_commit{
//   continuous_integration()
// }


on_pull_request to: dev, {
  
  continuous_integration()
  deploy_to development
}

on_pull_request to: main, {
  continuous_integration()
  deploy_to master
}

on_demand{
  continuous_integration()
  deploy_to test

}
on_merge to: main, {
  deploy_to prod

}




// continuous_integration()
